before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - main: ./cmd/sclient/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - freebsd
      - windows
      - js
    goarch:
      - amd64
      - arm
      - arm64
      - wasm
    goarm:
      - 7
    goamd64:
      - v2
    ignore:
      - goos: windows
        goarch: 386
      - goos: windows
        goarm: 6
      - goos: windows
        goarm: 7
archives:
  - id: sclient-binary
    format: tar.xz
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
